id         = "kq3"
title      = "King's Quest 3: To Heir Is Human"
platform   = "dos"
collection = "kings-quest"

[runtime]
emulator = "dosbox-staging"
config   = "../config/kq3.conf"
sidecars = ["fluidsynth"]

