[sdl]
fullscreen=false
fulldouble=false
fullresample=false
output=surface
autolock=true
sensitivity=100

[dosbox]
memsize=16
machine=svga_s3
captures=capture

[render]
frameskip=0
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[sblaster]
sbtype=sb16
sbport=220
sbirq=7
sbbase=23c0

[midi]
mididevice=default
midiconfig=

[speaker]
pctimer=true
pitch=49716

[joystick]
joysticktype=none

[general]
debugger=false
uidebug=false

[realmode]
safemode=false

[log]
log=false
logtimestamps=false

[misc]
capture=false

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.