id         = "qfg3"
title      = "Quest for Glory 3: Wages of War"
platform   = "dos"
collection = "quest-for-glory"

[runtime]
emulator = "dosbox-staging"
config   = "../config/qfg3.conf"
sidecars = ["fluidsynth"]

